/*
 * Used for undo, each action is saved
 * onto history
 */
define(function () {
    var history = [],
        // save up to 32 actions
        HISTORY_SIZE = 32;

    return {
        // Adds an action to the history
        // The history is basically a bunch of functions
        // which undo each action
        'add': function (fn) {
            // Check for limit, if reached remove first
            if(history.length > HISTORY_SIZE) {
                history.shift();
            }

            history.push(fn);
        },

        'undo': function () {
            if(history.length == 0) {
                return;
            }

            // Get the latest undo action
            var last = history.pop();
            // Call it
            last();
            // Remove the action generated by that function
            history.pop();
        }
    };
});
